#ifndef GUARD_CONSTANTS_HOENN_MAP_GROUPS_H
#define GUARD_CONSTANTS_HOENN_MAP_GROUPS_H

// Auto-generated from pokeruby map_groups.h
// Hoenn map groups start at group 43 (after FireRed's 43 groups)



// gMapGroup_TownsAndRoutes (Hoenn)
#define MAP_HOENN_PETALBURG_CITY                                     (0 | (43 << 8))
#define MAP_HOENN_SLATEPORT_CITY                                     (1 | (43 << 8))
#define MAP_HOENN_MAUVILLE_CITY                                      (2 | (43 << 8))
#define MAP_HOENN_RUSTBORO_CITY                                      (3 | (43 << 8))
#define MAP_HOENN_FORTREE_CITY                                       (4 | (43 << 8))
#define MAP_HOENN_LILYCOVE_CITY                                      (5 | (43 << 8))
#define MAP_HOENN_MOSSDEEP_CITY                                      (6 | (43 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY                                    (7 | (43 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY                                   (8 | (43 << 8))
#define MAP_HOENN_LITTLEROOT_TOWN                                    (9 | (43 << 8))
#define MAP_HOENN_OLDALE_TOWN                                        (10 | (43 << 8))
#define MAP_HOENN_DEWFORD_TOWN                                       (11 | (43 << 8))
#define MAP_HOENN_LAVARIDGE_TOWN                                     (12 | (43 << 8))
#define MAP_HOENN_FALLARBOR_TOWN                                     (13 | (43 << 8))
#define MAP_HOENN_VERDANTURF_TOWN                                    (14 | (43 << 8))
#define MAP_HOENN_PACIFIDLOG_TOWN                                    (15 | (43 << 8))
#define MAP_HOENN_ROUTE101                                           (16 | (43 << 8))
#define MAP_HOENN_ROUTE102                                           (17 | (43 << 8))
#define MAP_HOENN_ROUTE103                                           (18 | (43 << 8))
#define MAP_HOENN_ROUTE104                                           (19 | (43 << 8))
#define MAP_HOENN_ROUTE105                                           (20 | (43 << 8))
#define MAP_HOENN_ROUTE106                                           (21 | (43 << 8))
#define MAP_HOENN_ROUTE107                                           (22 | (43 << 8))
#define MAP_HOENN_ROUTE108                                           (23 | (43 << 8))
#define MAP_HOENN_ROUTE109                                           (24 | (43 << 8))
#define MAP_HOENN_ROUTE110                                           (25 | (43 << 8))
#define MAP_HOENN_ROUTE111                                           (26 | (43 << 8))
#define MAP_HOENN_ROUTE112                                           (27 | (43 << 8))
#define MAP_HOENN_ROUTE113                                           (28 | (43 << 8))
#define MAP_HOENN_ROUTE114                                           (29 | (43 << 8))
#define MAP_HOENN_ROUTE115                                           (30 | (43 << 8))
#define MAP_HOENN_ROUTE116                                           (31 | (43 << 8))
#define MAP_HOENN_ROUTE117                                           (32 | (43 << 8))
#define MAP_HOENN_ROUTE118                                           (33 | (43 << 8))
#define MAP_HOENN_ROUTE119                                           (34 | (43 << 8))
#define MAP_HOENN_ROUTE120                                           (35 | (43 << 8))
#define MAP_HOENN_ROUTE121                                           (36 | (43 << 8))
#define MAP_HOENN_ROUTE122                                           (37 | (43 << 8))
#define MAP_HOENN_ROUTE123                                           (38 | (43 << 8))
#define MAP_HOENN_ROUTE124                                           (39 | (43 << 8))
#define MAP_HOENN_ROUTE125                                           (40 | (43 << 8))
#define MAP_HOENN_ROUTE126                                           (41 | (43 << 8))
#define MAP_HOENN_ROUTE127                                           (42 | (43 << 8))
#define MAP_HOENN_ROUTE128                                           (43 | (43 << 8))
#define MAP_HOENN_ROUTE129                                           (44 | (43 << 8))
#define MAP_HOENN_ROUTE130                                           (45 | (43 << 8))
#define MAP_HOENN_ROUTE131                                           (46 | (43 << 8))
#define MAP_HOENN_ROUTE132                                           (47 | (43 << 8))
#define MAP_HOENN_ROUTE133                                           (48 | (43 << 8))
#define MAP_HOENN_ROUTE134                                           (49 | (43 << 8))
#define MAP_HOENN_UNDERWATER1                                        (50 | (43 << 8))
#define MAP_HOENN_UNDERWATER2                                        (51 | (43 << 8))
#define MAP_HOENN_UNDERWATER3                                        (52 | (43 << 8))
#define MAP_HOENN_UNDERWATER4                                        (53 | (43 << 8))

// gMapGroup_IndoorLittleroot (Hoenn)
#define MAP_HOENN_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F                  (0 | (44 << 8))
#define MAP_HOENN_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F                  (1 | (44 << 8))
#define MAP_HOENN_LITTLEROOT_TOWN_MAYS_HOUSE_1F                      (2 | (44 << 8))
#define MAP_HOENN_LITTLEROOT_TOWN_MAYS_HOUSE_2F                      (3 | (44 << 8))
#define MAP_HOENN_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB               (4 | (44 << 8))

// gMapGroup_IndoorOldale (Hoenn)
#define MAP_HOENN_OLDALE_TOWN_HOUSE1                                 (0 | (45 << 8))
#define MAP_HOENN_OLDALE_TOWN_HOUSE2                                 (1 | (45 << 8))
#define MAP_HOENN_OLDALE_TOWN_POKEMON_CENTER_1F                      (2 | (45 << 8))
#define MAP_HOENN_OLDALE_TOWN_POKEMON_CENTER_2F                      (3 | (45 << 8))
#define MAP_HOENN_OLDALE_TOWN_MART                                   (4 | (45 << 8))

// gMapGroup_IndoorDewford (Hoenn)
#define MAP_HOENN_DEWFORD_TOWN_HOUSE1                                (0 | (46 << 8))
#define MAP_HOENN_DEWFORD_TOWN_POKEMON_CENTER_1F                     (1 | (46 << 8))
#define MAP_HOENN_DEWFORD_TOWN_POKEMON_CENTER_2F                     (2 | (46 << 8))
#define MAP_HOENN_DEWFORD_TOWN_GYM                                   (3 | (46 << 8))
#define MAP_HOENN_DEWFORD_TOWN_HALL                                  (4 | (46 << 8))
#define MAP_HOENN_DEWFORD_TOWN_HOUSE2                                (5 | (46 << 8))

// gMapGroup_IndoorLavaridge (Hoenn)
#define MAP_HOENN_LAVARIDGE_TOWN_HERB_SHOP                           (0 | (47 << 8))
#define MAP_HOENN_LAVARIDGE_TOWN_GYM_1F                              (1 | (47 << 8))
#define MAP_HOENN_LAVARIDGE_TOWN_GYM_B1F                             (2 | (47 << 8))
#define MAP_HOENN_LAVARIDGE_TOWN_HOUSE                               (3 | (47 << 8))
#define MAP_HOENN_LAVARIDGE_TOWN_MART                                (4 | (47 << 8))
#define MAP_HOENN_LAVARIDGE_TOWN_POKEMON_CENTER_1F                   (5 | (47 << 8))
#define MAP_HOENN_LAVARIDGE_TOWN_POKEMON_CENTER_2F                   (6 | (47 << 8))

// gMapGroup_IndoorFallarbor (Hoenn)
#define MAP_HOENN_FALLARBOR_TOWN_MART                                (0 | (48 << 8))
#define MAP_HOENN_FALLARBOR_TOWN_CONTEST_LOBBY                       (1 | (48 << 8))
#define MAP_HOENN_FALLARBOR_TOWN_CONTEST_HALL                        (2 | (48 << 8))
#define MAP_HOENN_FALLARBOR_TOWN_POKEMON_CENTER_1F                   (3 | (48 << 8))
#define MAP_HOENN_FALLARBOR_TOWN_POKEMON_CENTER_2F                   (4 | (48 << 8))
#define MAP_HOENN_FALLARBOR_TOWN_HOUSE1                              (5 | (48 << 8))
#define MAP_HOENN_FALLARBOR_TOWN_HOUSE2                              (6 | (48 << 8))

// gMapGroup_IndoorVerdanturf (Hoenn)
#define MAP_HOENN_VERDANTURF_TOWN_CONTEST_LOBBY                      (0 | (49 << 8))
#define MAP_HOENN_VERDANTURF_TOWN_CONTEST_HALL                       (1 | (49 << 8))
#define MAP_HOENN_VERDANTURF_TOWN_MART                               (2 | (49 << 8))
#define MAP_HOENN_VERDANTURF_TOWN_POKEMON_CENTER_1F                  (3 | (49 << 8))
#define MAP_HOENN_VERDANTURF_TOWN_POKEMON_CENTER_2F                  (4 | (49 << 8))
#define MAP_HOENN_VERDANTURF_TOWN_WANDAS_HOUSE                       (5 | (49 << 8))
#define MAP_HOENN_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE            (6 | (49 << 8))
#define MAP_HOENN_VERDANTURF_TOWN_HOUSE                              (7 | (49 << 8))

// gMapGroup_IndoorPacifidlog (Hoenn)
#define MAP_HOENN_PACIFIDLOG_TOWN_POKEMON_CENTER_1F                  (0 | (50 << 8))
#define MAP_HOENN_PACIFIDLOG_TOWN_POKEMON_CENTER_2F                  (1 | (50 << 8))
#define MAP_HOENN_PACIFIDLOG_TOWN_HOUSE1                             (2 | (50 << 8))
#define MAP_HOENN_PACIFIDLOG_TOWN_HOUSE2                             (3 | (50 << 8))
#define MAP_HOENN_PACIFIDLOG_TOWN_HOUSE3                             (4 | (50 << 8))
#define MAP_HOENN_PACIFIDLOG_TOWN_HOUSE4                             (5 | (50 << 8))
#define MAP_HOENN_PACIFIDLOG_TOWN_HOUSE5                             (6 | (50 << 8))

// gMapGroup_IndoorPetalburg (Hoenn)
#define MAP_HOENN_PETALBURG_CITY_WALLYS_HOUSE                        (0 | (51 << 8))
#define MAP_HOENN_PETALBURG_CITY_GYM                                 (1 | (51 << 8))
#define MAP_HOENN_PETALBURG_CITY_HOUSE1                              (2 | (51 << 8))
#define MAP_HOENN_PETALBURG_CITY_HOUSE2                              (3 | (51 << 8))
#define MAP_HOENN_PETALBURG_CITY_POKEMON_CENTER_1F                   (4 | (51 << 8))
#define MAP_HOENN_PETALBURG_CITY_POKEMON_CENTER_2F                   (5 | (51 << 8))
#define MAP_HOENN_PETALBURG_CITY_MART                                (6 | (51 << 8))

// gMapGroup_IndoorSlateport (Hoenn)
#define MAP_HOENN_SLATEPORT_CITY_STERNS_SHIPYARD_1F                  (0 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_STERNS_SHIPYARD_2F                  (1 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_CONTEST_LOBBY                       (2 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_CONTEST_HALL                        (3 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_HOUSE1                              (4 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_POKEMON_FAN_CLUB                    (5 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_OCEANIC_MUSEUM_1F                   (6 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_OCEANIC_MUSEUM_2F                   (7 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_HARBOR                              (8 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_HOUSE2                              (9 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_POKEMON_CENTER_1F                   (10 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_POKEMON_CENTER_2F                   (11 | (52 << 8))
#define MAP_HOENN_SLATEPORT_CITY_MART                                (12 | (52 << 8))

// gMapGroup_IndoorMauville (Hoenn)
#define MAP_HOENN_MAUVILLE_CITY_GYM                                  (0 | (53 << 8))
#define MAP_HOENN_MAUVILLE_CITY_BIKE_SHOP                            (1 | (53 << 8))
#define MAP_HOENN_MAUVILLE_CITY_HOUSE1                               (2 | (53 << 8))
#define MAP_HOENN_MAUVILLE_CITY_GAME_CORNER                          (3 | (53 << 8))
#define MAP_HOENN_MAUVILLE_CITY_HOUSE2                               (4 | (53 << 8))
#define MAP_HOENN_MAUVILLE_CITY_POKEMON_CENTER_1F                    (5 | (53 << 8))
#define MAP_HOENN_MAUVILLE_CITY_POKEMON_CENTER_2F                    (6 | (53 << 8))
#define MAP_HOENN_MAUVILLE_CITY_MART                                 (7 | (53 << 8))

// gMapGroup_IndoorRustboro (Hoenn)
#define MAP_HOENN_RUSTBORO_CITY_DEVON_CORP_1F                        (0 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_DEVON_CORP_2F                        (1 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_DEVON_CORP_3F                        (2 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_GYM                                  (3 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_POKEMON_SCHOOL                       (4 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_POKEMON_CENTER_1F                    (5 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_POKEMON_CENTER_2F                    (6 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_MART                                 (7 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_FLAT1_1F                             (8 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_FLAT1_2F                             (9 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_HOUSE1                               (10 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_CUTTERS_HOUSE                        (11 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_HOUSE2                               (12 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_FLAT2_1F                             (13 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_FLAT2_2F                             (14 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_FLAT2_3F                             (15 | (54 << 8))
#define MAP_HOENN_RUSTBORO_CITY_HOUSE3                               (16 | (54 << 8))

// gMapGroup_IndoorFortree (Hoenn)
#define MAP_HOENN_FORTREE_CITY_HOUSE1                                (0 | (55 << 8))
#define MAP_HOENN_FORTREE_CITY_GYM                                   (1 | (55 << 8))
#define MAP_HOENN_FORTREE_CITY_POKEMON_CENTER_1F                     (2 | (55 << 8))
#define MAP_HOENN_FORTREE_CITY_POKEMON_CENTER_2F                     (3 | (55 << 8))
#define MAP_HOENN_FORTREE_CITY_MART                                  (4 | (55 << 8))
#define MAP_HOENN_FORTREE_CITY_HOUSE2                                (5 | (55 << 8))
#define MAP_HOENN_FORTREE_CITY_HOUSE3                                (6 | (55 << 8))
#define MAP_HOENN_FORTREE_CITY_HOUSE4                                (7 | (55 << 8))
#define MAP_HOENN_FORTREE_CITY_HOUSE5                                (8 | (55 << 8))
#define MAP_HOENN_FORTREE_CITY_DECORATION_SHOP                       (9 | (55 << 8))

// gMapGroup_IndoorLilycove (Hoenn)
#define MAP_HOENN_LILYCOVE_CITY_COVE_LILY_MOTEL_1F                   (0 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_COVE_LILY_MOTEL_2F                   (1 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F                   (2 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F                   (3 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_CONTEST_LOBBY                        (4 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_CONTEST_HALL                         (5 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_POKEMON_CENTER_1F                    (6 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_POKEMON_CENTER_2F                    (7 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_UNUSED_MART                          (8 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB             (9 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_HARBOR                               (10 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_EMPTY_MAP                            (11 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_MOVE_DELETERS_HOUSE                  (12 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_HOUSE1                               (13 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_HOUSE2                               (14 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_HOUSE3                               (15 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_HOUSE4                               (16 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_DEPARTMENT_STORE_1F                  (17 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_DEPARTMENT_STORE_2F                  (18 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_DEPARTMENT_STORE_3F                  (19 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_DEPARTMENT_STORE_4F                  (20 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_DEPARTMENT_STORE_5F                  (21 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP             (22 | (56 << 8))
#define MAP_HOENN_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR            (23 | (56 << 8))

// gMapGroup_IndoorMossdeep (Hoenn)
#define MAP_HOENN_MOSSDEEP_CITY_GYM                                  (0 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_HOUSE1                               (1 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_HOUSE2                               (2 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_POKEMON_CENTER_1F                    (3 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_POKEMON_CENTER_2F                    (4 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_MART                                 (5 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_HOUSE3                               (6 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_STEVENS_HOUSE                        (7 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_HOUSE4                               (8 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_SPACE_CENTER_1F                      (9 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_SPACE_CENTER_2F                      (10 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_GAME_CORNER_1F                       (11 | (57 << 8))
#define MAP_HOENN_MOSSDEEP_CITY_GAME_CORNER_B1F                      (12 | (57 << 8))

// gMapGroup_IndoorSootopolis (Hoenn)
#define MAP_HOENN_SOOTOPOLIS_CITY_GYM_1F                             (0 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_GYM_B1F                            (1 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_POKEMON_CENTER_1F                  (2 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_POKEMON_CENTER_2F                  (3 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_MART                               (4 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_HOUSE1                             (5 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_HOUSE2                             (6 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_HOUSE3                             (7 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_HOUSE4                             (8 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_HOUSE5                             (9 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_HOUSE6                             (10 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_HOUSE7                             (11 | (58 << 8))
#define MAP_HOENN_SOOTOPOLIS_CITY_HOUSE8                             (12 | (58 << 8))

// gMapGroup_IndoorEverGrande (Hoenn)
#define MAP_HOENN_EVER_GRANDE_CITY_SIDNEYS_ROOM                      (0 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_PHOEBES_ROOM                      (1 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_GLACIAS_ROOM                      (2 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_DRAKES_ROOM                       (3 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_CHAMPIONS_ROOM                    (4 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_CORRIDOR1                         (5 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_CORRIDOR2                         (6 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_CORRIDOR3                         (7 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_CORRIDOR4                         (8 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_CORRIDOR5                         (9 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_POKEMON_LEAGUE                    (10 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_HALL_OF_FAME                      (11 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_POKEMON_CENTER_1F                 (12 | (59 << 8))
#define MAP_HOENN_EVER_GRANDE_CITY_POKEMON_CENTER_2F                 (13 | (59 << 8))

// gMapGroup_IndoorRoute104 (Hoenn)
#define MAP_HOENN_ROUTE104_MR_BRINEYS_HOUSE                          (0 | (60 << 8))
#define MAP_HOENN_ROUTE104_PRETTY_PETAL_FLOWER_SHOP                  (1 | (60 << 8))

// gMapGroup_IndoorRoute111 (Hoenn)
#define MAP_HOENN_ROUTE111_WINSTRATE_FAMILYS_HOUSE                   (0 | (61 << 8))
#define MAP_HOENN_ROUTE111_OLD_LADYS_REST_STOP                       (1 | (61 << 8))

// gMapGroup_IndoorRoute112 (Hoenn)
#define MAP_HOENN_ROUTE112_CABLE_CAR_STATION                         (0 | (62 << 8))
#define MAP_HOENN_MT_CHIMNEY_CABLE_CAR_STATION                       (1 | (62 << 8))

// gMapGroup_IndoorRoute114 (Hoenn)
#define MAP_HOENN_ROUTE114_FOSSIL_MANIACS_HOUSE                      (0 | (63 << 8))
#define MAP_HOENN_ROUTE114_FOSSIL_MANIACS_TUNNEL                     (1 | (63 << 8))
#define MAP_HOENN_ROUTE114_LANETTES_HOUSE                            (2 | (63 << 8))

// gMapGroup_IndoorRoute116 (Hoenn)
#define MAP_HOENN_ROUTE116_TUNNELERS_REST_HOUSE                      (0 | (64 << 8))

// gMapGroup_IndoorRoute117 (Hoenn)
#define MAP_HOENN_ROUTE117_POKEMON_DAY_CARE                          (0 | (65 << 8))

// gMapGroup_IndoorRoute121 (Hoenn)
#define MAP_HOENN_ROUTE121_SAFARI_ZONE_ENTRANCE                      (0 | (66 << 8))

// gMapGroup_Dungeons (Hoenn)
#define MAP_HOENN_METEOR_FALLS_1F_1R                                 (0 | (67 << 8))
#define MAP_HOENN_METEOR_FALLS_1F_2R                                 (1 | (67 << 8))
#define MAP_HOENN_METEOR_FALLS_B1F_1R                                (2 | (67 << 8))
#define MAP_HOENN_METEOR_FALLS_B1F_2R                                (3 | (67 << 8))
#define MAP_HOENN_RUSTURF_TUNNEL                                     (4 | (67 << 8))
#define MAP_HOENN_UNDERWATER_SOOTOPOLIS_CITY                         (5 | (67 << 8))
#define MAP_HOENN_DESERT_RUINS                                       (6 | (67 << 8))
#define MAP_HOENN_GRANITE_CAVE_1F                                    (7 | (67 << 8))
#define MAP_HOENN_GRANITE_CAVE_B1F                                   (8 | (67 << 8))
#define MAP_HOENN_GRANITE_CAVE_B2F                                   (9 | (67 << 8))
#define MAP_HOENN_GRANITE_CAVE_STEVENS_ROOM                          (10 | (67 << 8))
#define MAP_HOENN_PETALBURG_WOODS                                    (11 | (67 << 8))
#define MAP_HOENN_MT_CHIMNEY                                         (12 | (67 << 8))
#define MAP_HOENN_JAGGED_PASS                                        (13 | (67 << 8))
#define MAP_HOENN_FIERY_PATH                                         (14 | (67 << 8))
#define MAP_HOENN_MT_PYRE_1F                                         (15 | (67 << 8))
#define MAP_HOENN_MT_PYRE_2F                                         (16 | (67 << 8))
#define MAP_HOENN_MT_PYRE_3F                                         (17 | (67 << 8))
#define MAP_HOENN_MT_PYRE_4F                                         (18 | (67 << 8))
#define MAP_HOENN_MT_PYRE_5F                                         (19 | (67 << 8))
#define MAP_HOENN_MT_PYRE_6F                                         (20 | (67 << 8))
#define MAP_HOENN_MT_PYRE_EXTERIOR                                   (21 | (67 << 8))
#define MAP_HOENN_MT_PYRE_SUMMIT                                     (22 | (67 << 8))
#define MAP_HOENN_AQUA_HIDEOUT_1F                                    (23 | (67 << 8))
#define MAP_HOENN_AQUA_HIDEOUT_B1F                                   (24 | (67 << 8))
#define MAP_HOENN_AQUA_HIDEOUT_B2F                                   (25 | (67 << 8))
#define MAP_HOENN_UNDERWATER_SEAFLOOR_CAVERN                         (26 | (67 << 8))
#define MAP_HOENN_SEAFLOOR_CAVERN_ENTRANCE                           (27 | (67 << 8))
#define MAP_HOENN_SEAFLOOR_CAVERN_ROOM1                              (28 | (67 << 8))
#define MAP_HOENN_SEAFLOOR_CAVERN_ROOM2                              (29 | (67 << 8))
#define MAP_HOENN_SEAFLOOR_CAVERN_ROOM3                              (30 | (67 << 8))
#define MAP_HOENN_SEAFLOOR_CAVERN_ROOM4                              (31 | (67 << 8))
#define MAP_HOENN_SEAFLOOR_CAVERN_ROOM5                              (32 | (67 << 8))
#define MAP_HOENN_SEAFLOOR_CAVERN_ROOM6                              (33 | (67 << 8))
#define MAP_HOENN_SEAFLOOR_CAVERN_ROOM7                              (34 | (67 << 8))
#define MAP_HOENN_SEAFLOOR_CAVERN_ROOM8                              (35 | (67 << 8))
#define MAP_HOENN_SEAFLOOR_CAVERN_ROOM9                              (36 | (67 << 8))
#define MAP_HOENN_CAVE_OF_ORIGIN_ENTRANCE                            (37 | (67 << 8))
#define MAP_HOENN_CAVE_OF_ORIGIN_1F                                  (38 | (67 << 8))
#define MAP_HOENN_CAVE_OF_ORIGIN_B1F                                 (39 | (67 << 8))
#define MAP_HOENN_CAVE_OF_ORIGIN_B2F                                 (40 | (67 << 8))
#define MAP_HOENN_CAVE_OF_ORIGIN_B3F                                 (41 | (67 << 8))
#define MAP_HOENN_CAVE_OF_ORIGIN_B4F                                 (42 | (67 << 8))
#define MAP_HOENN_VICTORY_ROAD_1F                                    (43 | (67 << 8))
#define MAP_HOENN_VICTORY_ROAD_B1F                                   (44 | (67 << 8))
#define MAP_HOENN_VICTORY_ROAD_B2F                                   (45 | (67 << 8))
#define MAP_HOENN_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM                  (46 | (67 << 8))
#define MAP_HOENN_SHOAL_CAVE_LOW_TIDE_INNER_ROOM                     (47 | (67 << 8))
#define MAP_HOENN_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM                    (48 | (67 << 8))
#define MAP_HOENN_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM                     (49 | (67 << 8))
#define MAP_HOENN_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM                 (50 | (67 << 8))
#define MAP_HOENN_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM                    (51 | (67 << 8))
#define MAP_HOENN_NEW_MAUVILLE_ENTRANCE                              (52 | (67 << 8))
#define MAP_HOENN_NEW_MAUVILLE_INSIDE                                (53 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_DECK                                (54 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_CORRIDORS_1F                        (55 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_ROOMS_1F                            (56 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_CORRIDORS_B1F                       (57 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_ROOMS_B1F                           (58 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_ROOMS2_B1F                          (59 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_UNDERWATER1                         (60 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_ROOM_B1F                            (61 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_ROOMS2_1F                           (62 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_CAPTAINS_OFFICE                     (63 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_UNDERWATER2                         (64 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS              (65 | (67 << 8))
#define MAP_HOENN_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS                  (66 | (67 << 8))
#define MAP_HOENN_ISLAND_CAVE                                        (67 | (67 << 8))
#define MAP_HOENN_ANCIENT_TOMB                                       (68 | (67 << 8))
#define MAP_HOENN_UNDERWATER_ROUTE134                                (69 | (67 << 8))
#define MAP_HOENN_UNDERWATER_SEALED_CHAMBER                          (70 | (67 << 8))
#define MAP_HOENN_SEALED_CHAMBER_OUTER_ROOM                          (71 | (67 << 8))
#define MAP_HOENN_SEALED_CHAMBER_INNER_ROOM                          (72 | (67 << 8))
#define MAP_HOENN_SCORCHED_SLAB                                      (73 | (67 << 8))
#define MAP_HOENN_MAGMA_HIDEOUT_1F                                   (74 | (67 << 8))
#define MAP_HOENN_MAGMA_HIDEOUT_B1F                                  (75 | (67 << 8))
#define MAP_HOENN_MAGMA_HIDEOUT_B2F                                  (76 | (67 << 8))
#define MAP_HOENN_SKY_PILLAR_ENTRANCE                                (77 | (67 << 8))
#define MAP_HOENN_SKY_PILLAR_OUTSIDE                                 (78 | (67 << 8))
#define MAP_HOENN_SKY_PILLAR_1F                                      (79 | (67 << 8))
#define MAP_HOENN_SKY_PILLAR_2F                                      (80 | (67 << 8))
#define MAP_HOENN_SKY_PILLAR_3F                                      (81 | (67 << 8))
#define MAP_HOENN_SKY_PILLAR_4F                                      (82 | (67 << 8))
#define MAP_HOENN_SHOAL_CAVE_LOW_TIDE_ICE_ROOM                       (83 | (67 << 8))
#define MAP_HOENN_SKY_PILLAR_5F                                      (84 | (67 << 8))
#define MAP_HOENN_SKY_PILLAR_TOP                                     (85 | (67 << 8))

// gMapGroup_IndoorDynamic (Hoenn)
#define MAP_HOENN_SECRET_BASE_RED_CAVE1                              (0 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_BROWN_CAVE1                            (1 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_BLUE_CAVE1                             (2 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_YELLOW_CAVE1                           (3 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_TREE1                                  (4 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_SHRUB1                                 (5 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_RED_CAVE2                              (6 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_BROWN_CAVE2                            (7 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_BLUE_CAVE2                             (8 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_YELLOW_CAVE2                           (9 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_TREE2                                  (10 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_SHRUB2                                 (11 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_RED_CAVE3                              (12 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_BROWN_CAVE3                            (13 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_BLUE_CAVE3                             (14 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_YELLOW_CAVE3                           (15 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_TREE3                                  (16 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_SHRUB3                                 (17 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_RED_CAVE4                              (18 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_BROWN_CAVE4                            (19 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_BLUE_CAVE4                             (20 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_YELLOW_CAVE4                           (21 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_TREE4                                  (22 | (68 << 8))
#define MAP_HOENN_SECRET_BASE_SHRUB4                                 (23 | (68 << 8))
#define MAP_HOENN_SINGLE_BATTLE_COLOSSEUM                            (24 | (68 << 8))
#define MAP_HOENN_TRADE_CENTER                                       (25 | (68 << 8))
#define MAP_HOENN_RECORD_CORNER                                      (26 | (68 << 8))
#define MAP_HOENN_DOUBLE_BATTLE_COLOSSEUM                            (27 | (68 << 8))
#define MAP_HOENN_LINK_CONTEST_ROOM1                                 (28 | (68 << 8))
#define MAP_HOENN_UNKNOWN_MAP_25_29                                  (29 | (68 << 8))
#define MAP_HOENN_UNKNOWN_MAP_25_30                                  (30 | (68 << 8))
#define MAP_HOENN_UNKNOWN_MAP_25_31                                  (31 | (68 << 8))
#define MAP_HOENN_UNKNOWN_MAP_25_32                                  (32 | (68 << 8))
#define MAP_HOENN_UNKNOWN_MAP_25_33                                  (33 | (68 << 8))
#define MAP_HOENN_UNKNOWN_MAP_25_34                                  (34 | (68 << 8))
#define MAP_HOENN_LINK_CONTEST_ROOM2                                 (35 | (68 << 8))
#define MAP_HOENN_LINK_CONTEST_ROOM3                                 (36 | (68 << 8))
#define MAP_HOENN_LINK_CONTEST_ROOM4                                 (37 | (68 << 8))
#define MAP_HOENN_LINK_CONTEST_ROOM5                                 (38 | (68 << 8))
#define MAP_HOENN_LINK_CONTEST_ROOM6                                 (39 | (68 << 8))
#define MAP_HOENN_INSIDE_OF_TRUCK                                    (40 | (68 << 8))
#define MAP_HOENN_SS_TIDAL_CORRIDOR                                  (41 | (68 << 8))
#define MAP_HOENN_SS_TIDAL_LOWER_DECK                                (42 | (68 << 8))
#define MAP_HOENN_SS_TIDAL_ROOMS                                     (43 | (68 << 8))

// gMapGroup_SpecialArea (Hoenn)
#define MAP_HOENN_SAFARI_ZONE_NORTHWEST                              (0 | (69 << 8))
#define MAP_HOENN_SAFARI_ZONE_NORTHEAST                              (1 | (69 << 8))
#define MAP_HOENN_SAFARI_ZONE_SOUTHWEST                              (2 | (69 << 8))
#define MAP_HOENN_SAFARI_ZONE_SOUTHEAST                              (3 | (69 << 8))
#define MAP_HOENN_BATTLE_TOWER_OUTSIDE                               (4 | (69 << 8))
#define MAP_HOENN_BATTLE_TOWER_LOBBY                                 (5 | (69 << 8))
#define MAP_HOENN_BATTLE_TOWER_ELEVATOR                              (6 | (69 << 8))
#define MAP_HOENN_BATTLE_TOWER_CORRIDOR                              (7 | (69 << 8))
#define MAP_HOENN_BATTLE_TOWER_BATTLE_ROOM                           (8 | (69 << 8))
#define MAP_HOENN_SOUTHERN_ISLAND_EXTERIOR                           (9 | (69 << 8))
#define MAP_HOENN_SOUTHERN_ISLAND_INTERIOR                           (10 | (69 << 8))
#define MAP_HOENN_SAFARI_ZONE_REST_HOUSE                             (11 | (69 << 8))

// gMapGroup_IndoorRoute104Prototype (Hoenn)
#define MAP_HOENN_ROUTE104_PROTOTYPE                                 (0 | (70 << 8))
#define MAP_HOENN_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP        (1 | (70 << 8))

// gMapGroup_IndoorRoute109 (Hoenn)
#define MAP_HOENN_ROUTE109_SEASHORE_HOUSE                            (0 | (71 << 8))

// gMapGroup_IndoorRoute110 (Hoenn)
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_ENTRANCE                      (0 | (72 << 8))
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_END                           (1 | (72 << 8))
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_CORRIDOR                      (2 | (72 << 8))
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_PUZZLE1                       (3 | (72 << 8))
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_PUZZLE2                       (4 | (72 << 8))
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_PUZZLE3                       (5 | (72 << 8))
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_PUZZLE4                       (6 | (72 << 8))
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_PUZZLE5                       (7 | (72 << 8))
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_PUZZLE6                       (8 | (72 << 8))
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_PUZZLE7                       (9 | (72 << 8))
#define MAP_HOENN_ROUTE110_TRICK_HOUSE_PUZZLE8                       (10 | (72 << 8))
#define MAP_HOENN_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE       (11 | (72 << 8))
#define MAP_HOENN_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE       (12 | (72 << 8))

// gMapGroup_IndoorRoute113 (Hoenn)
#define MAP_HOENN_ROUTE113_GLASS_WORKSHOP                            (0 | (73 << 8))

// gMapGroup_IndoorRoute123 (Hoenn)
#define MAP_HOENN_ROUTE123_BERRY_MASTERS_HOUSE                       (0 | (74 << 8))

// gMapGroup_IndoorRoute119 (Hoenn)
#define MAP_HOENN_ROUTE119_WEATHER_INSTITUTE_1F                      (0 | (75 << 8))
#define MAP_HOENN_ROUTE119_WEATHER_INSTITUTE_2F                      (1 | (75 << 8))
#define MAP_HOENN_ROUTE119_HOUSE                                     (2 | (75 << 8))

// gMapGroup_IndoorRoute124 (Hoenn)
#define MAP_HOENN_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE             (0 | (76 << 8))


#define HOENN_MAP_GROUPS_COUNT 34
#define MAP_GROUPS_COUNT_WITH_HOENN (43 + 34)


// Total Hoenn maps: 394

#endif // GUARD_CONSTANTS_HOENN_MAP_GROUPS_H
