#ifndef GUARD_CONSTANTS_HOENN_H
#define GUARD_CONSTANTS_HOENN_H

// Hoenn flag/var routing bases
// Flags >= HOENN_FLAGS_BASE route to gSaveBlock1Ptr->hoennFlags
// Vars >= HOENN_VARS_BASE route to gSaveBlock1Ptr->hoennVars
#define HOENN_FLAGS_BASE    0x1000
#define HOENN_FLAGS_COUNT   0x900
#define HOENN_VARS_BASE     0x5000
#define HOENN_VARS_COUNT    256

// Hoenn trainer ID offset (appended after FireRed's trainers)
#define HOENN_TRAINER_BASE  768

// Hoenn map group offset (appended after FireRed's 43 groups)
#define HOENN_MAP_GROUP_BASE 43

// Hoenn song ID offset
#define HOENN_SONG_BASE     400

// Hoenn layout ID offset
#define HOENN_LAYOUT_BASE   300

// Hoenn MAPSEC offset (appended after FireRed's region map sections)
#define HOENN_MAPSEC_BASE   210

// Flag set by Daisy's Town Map upgrade
#define FLAG_HOENN_MAP_UNLOCKED 0x8E1

// Hoenn system flags (offset from HOENN_FLAGS_BASE)
#define HFLAG_SYS_POKEMON_GET       (HOENN_FLAGS_BASE + 0x800)
#define HFLAG_SYS_POKEDEX_GET       (HOENN_FLAGS_BASE + 0x801)
#define HFLAG_SYS_GAME_CLEAR        (HOENN_FLAGS_BASE + 0x804)
#define HFLAG_BADGE01_GET            (HOENN_FLAGS_BASE + 0x807)
#define HFLAG_BADGE02_GET            (HOENN_FLAGS_BASE + 0x808)
#define HFLAG_BADGE03_GET            (HOENN_FLAGS_BASE + 0x809)
#define HFLAG_BADGE04_GET            (HOENN_FLAGS_BASE + 0x80A)
#define HFLAG_BADGE05_GET            (HOENN_FLAGS_BASE + 0x80B)
#define HFLAG_BADGE06_GET            (HOENN_FLAGS_BASE + 0x80C)
#define HFLAG_BADGE07_GET            (HOENN_FLAGS_BASE + 0x80D)
#define HFLAG_BADGE08_GET            (HOENN_FLAGS_BASE + 0x80E)
#define HFLAG_VISITED_LITTLEROOT     (HOENN_FLAGS_BASE + 0x80F)
#define HFLAG_VISITED_OLDALE         (HOENN_FLAGS_BASE + 0x810)
#define HFLAG_VISITED_DEWFORD        (HOENN_FLAGS_BASE + 0x811)
#define HFLAG_VISITED_LAVARIDGE      (HOENN_FLAGS_BASE + 0x812)
#define HFLAG_VISITED_FALLARBOR      (HOENN_FLAGS_BASE + 0x813)
#define HFLAG_VISITED_VERDANTURF     (HOENN_FLAGS_BASE + 0x814)
#define HFLAG_VISITED_PACIFIDLOG     (HOENN_FLAGS_BASE + 0x815)
#define HFLAG_VISITED_PETALBURG      (HOENN_FLAGS_BASE + 0x816)
#define HFLAG_VISITED_SLATEPORT      (HOENN_FLAGS_BASE + 0x817)
#define HFLAG_VISITED_MAUVILLE       (HOENN_FLAGS_BASE + 0x818)
#define HFLAG_VISITED_RUSTBORO       (HOENN_FLAGS_BASE + 0x819)
#define HFLAG_VISITED_FORTREE        (HOENN_FLAGS_BASE + 0x81A)
#define HFLAG_VISITED_LILYCOVE       (HOENN_FLAGS_BASE + 0x81B)
#define HFLAG_VISITED_MOSSDEEP       (HOENN_FLAGS_BASE + 0x81C)
#define HFLAG_VISITED_SOOTOPOLIS     (HOENN_FLAGS_BASE + 0x81D)
#define HFLAG_VISITED_EVER_GRANDE    (HOENN_FLAGS_BASE + 0x81E)

// Story progression flags
#define HFLAG_GOT_STARTER           (HOENN_FLAGS_BASE + 0x820)
#define HFLAG_MET_BIRCH             (HOENN_FLAGS_BASE + 0x821)
#define HFLAG_DEFEATED_ROXANNE      (HOENN_FLAGS_BASE + 0x830)
#define HFLAG_DEFEATED_BRAWLY       (HOENN_FLAGS_BASE + 0x831)
#define HFLAG_DEFEATED_WATTSON      (HOENN_FLAGS_BASE + 0x832)
#define HFLAG_DEFEATED_FLANNERY     (HOENN_FLAGS_BASE + 0x833)
#define HFLAG_DEFEATED_NORMAN       (HOENN_FLAGS_BASE + 0x834)
#define HFLAG_DEFEATED_WINONA       (HOENN_FLAGS_BASE + 0x835)
#define HFLAG_DEFEATED_LIZA_TATE    (HOENN_FLAGS_BASE + 0x836)
#define HFLAG_DEFEATED_WALLACE      (HOENN_FLAGS_BASE + 0x837)
#define HFLAG_DEFEATED_SIDNEY       (HOENN_FLAGS_BASE + 0x840)
#define HFLAG_DEFEATED_PHOEBE       (HOENN_FLAGS_BASE + 0x841)
#define HFLAG_DEFEATED_GLACIA       (HOENN_FLAGS_BASE + 0x842)
#define HFLAG_DEFEATED_DRAKE        (HOENN_FLAGS_BASE + 0x843)
#define HFLAG_DEFEATED_STEVEN       (HOENN_FLAGS_BASE + 0x844)

// Hoenn vars
#define HVAR_STARTER_CHOICE         (HOENN_VARS_BASE + 0x00)

#endif // GUARD_CONSTANTS_HOENN_H
