"""Build complete Ruby GFX -> FireRed GFX mapping for ALL Ruby sprites."""
import re

fr = {}
with open(r'c:\Users\hyper\projects\pokefirered-native\pokefirered\include\constants\event_objects.h') as f:
    for line in f:
        m = re.match(r'#define (OBJ_EVENT_GFX_\w+)\s+(\d+)', line)
        if m: fr[m.group(1)] = int(m.group(2))

rb = {}
with open(r'c:\Users\hyper\projects\pokefirered-native\pokeruby\include\constants\event_objects.h') as f:
    for line in f:
        m = re.match(r'#define (OBJ_EVENT_GFX_\w+)\s+(\d+)', line)
        if m: rb[m.group(1)] = int(m.group(2))

# Complete mapping: Ruby name -> FireRed numeric value
# For shared names, use FR value. For Ruby-only, map to closest FR equivalent.
COMPLETE = {}

# Direct name matches (same name, possibly different value)
for name in rb:
    if name in fr:
        COMPLETE[name] = fr[name]

# Manual mappings for Ruby-specific sprites
FR = fr  # shorthand
FB = fr.get('OBJ_EVENT_GFX_BOY_1', 1)  # fallback

manual = {
    # Ruby characters
    'OBJ_EVENT_GFX_PROF_BIRCH': FR.get('OBJ_EVENT_GFX_PROF_OAK', FB),
    'OBJ_EVENT_GFX_BRENDAN_NORMAL': FR.get('OBJ_EVENT_GFX_RED_NORMAL', FB),
    'OBJ_EVENT_GFX_BRENDAN_MACH_BIKE': 0,
    'OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE': 0,
    'OBJ_EVENT_GFX_BRENDAN_SURFING': 0,
    'OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE': 0,
    'OBJ_EVENT_GFX_BRENDAN_UNDERWATER': 0,
    'OBJ_EVENT_GFX_BRENDAN_WATERING': FR.get('OBJ_EVENT_GFX_RED_NORMAL', FB),
    'OBJ_EVENT_GFX_BRENDAN_FISHING': 0,
    'OBJ_EVENT_GFX_MAY_NORMAL': FR.get('OBJ_EVENT_GFX_GREEN', FB),
    'OBJ_EVENT_GFX_MAY_MACH_BIKE': 0,
    'OBJ_EVENT_GFX_MAY_ACRO_BIKE': 0,
    'OBJ_EVENT_GFX_MAY_SURFING': 0,
    'OBJ_EVENT_GFX_MAY_FIELD_MOVE': 0,
    'OBJ_EVENT_GFX_MAY_UNDERWATER': 0,
    'OBJ_EVENT_GFX_MAY_WATERING': FR.get('OBJ_EVENT_GFX_GREEN', FB),
    'OBJ_EVENT_GFX_MAY_FISHING': 0,
    # Villains
    'OBJ_EVENT_GFX_ARCHIE': FR.get('OBJ_EVENT_GFX_GIOVANNI', FB),
    'OBJ_EVENT_GFX_MAXIE': FR.get('OBJ_EVENT_GFX_GIOVANNI', FB),
    'OBJ_EVENT_GFX_AQUA_MEMBER_M': FR.get('OBJ_EVENT_GFX_ROCKET_M', FB),
    'OBJ_EVENT_GFX_AQUA_MEMBER_F': FR.get('OBJ_EVENT_GFX_ROCKET_F', FB),
    'OBJ_EVENT_GFX_MAGMA_MEMBER_M': FR.get('OBJ_EVENT_GFX_ROCKET_M', FB),
    'OBJ_EVENT_GFX_MAGMA_MEMBER_F': FR.get('OBJ_EVENT_GFX_ROCKET_F', FB),
    # Characters
    'OBJ_EVENT_GFX_WALLY': FR.get('OBJ_EVENT_GFX_BOY_2', FB),
    'OBJ_EVENT_GFX_SCOTT': FR.get('OBJ_EVENT_GFX_GENTLEMAN', FB),
    'OBJ_EVENT_GFX_MR_BRINEY': FR.get('OBJ_EVENT_GFX_OLD_MAN_1', FB),
    'OBJ_EVENT_GFX_STEVEN': FR.get('OBJ_EVENT_GFX_COOLTRAINER_M', FB),
    # Gym leaders
    'OBJ_EVENT_GFX_ROXANNE': FR.get('OBJ_EVENT_GFX_LASS', FB),
    'OBJ_EVENT_GFX_BRAWLY': FR.get('OBJ_EVENT_GFX_BLACK_BELT', FB),
    'OBJ_EVENT_GFX_WATTSON': FR.get('OBJ_EVENT_GFX_FAT_MAN', FB),
    'OBJ_EVENT_GFX_FLANNERY': FR.get('OBJ_EVENT_GFX_BEAUTY', FB),
    'OBJ_EVENT_GFX_NORMAN': FR.get('OBJ_EVENT_GFX_MAN_1', FR.get('OBJ_EVENT_GFX_OLD_MAN_1', FB)),
    'OBJ_EVENT_GFX_WINONA': FR.get('OBJ_EVENT_GFX_WOMAN_2', FB),
    'OBJ_EVENT_GFX_LIZA': FR.get('OBJ_EVENT_GFX_TWIN', FB),
    'OBJ_EVENT_GFX_TATE': FR.get('OBJ_EVENT_GFX_TWIN', FB),
    'OBJ_EVENT_GFX_WALLACE': FR.get('OBJ_EVENT_GFX_GENTLEMAN', FB),
    'OBJ_EVENT_GFX_JUAN': FR.get('OBJ_EVENT_GFX_GENTLEMAN', FB),
    'OBJ_EVENT_GFX_SIDNEY': FR.get('OBJ_EVENT_GFX_COOLTRAINER_M', FB),
    'OBJ_EVENT_GFX_PHOEBE': FR.get('OBJ_EVENT_GFX_BEAUTY', FB),
    'OBJ_EVENT_GFX_GLACIA': FR.get('OBJ_EVENT_GFX_WOMAN_2', FB),
    'OBJ_EVENT_GFX_DRAKE': FR.get('OBJ_EVENT_GFX_OLD_MAN_1', FB),
    # NPC types
    'OBJ_EVENT_GFX_BOY_1': FR.get('OBJ_EVENT_GFX_BOY_1', FB),
    'OBJ_EVENT_GFX_BOY_2': FR.get('OBJ_EVENT_GFX_BOY_2', FB),
    'OBJ_EVENT_GFX_BOY_3': FR.get('OBJ_EVENT_GFX_BOY_1', FB),
    'OBJ_EVENT_GFX_BOY_4': FR.get('OBJ_EVENT_GFX_BOY_2', FB),
    'OBJ_EVENT_GFX_BOY_5': FR.get('OBJ_EVENT_GFX_BOY_1', FB),
    'OBJ_EVENT_GFX_GIRL_1': FR.get('OBJ_EVENT_GFX_GIRL_1', FB),
    'OBJ_EVENT_GFX_GIRL_2': FR.get('OBJ_EVENT_GFX_GIRL_2', FB),
    'OBJ_EVENT_GFX_GIRL_3': FR.get('OBJ_EVENT_GFX_GIRL_1', FB),
    'OBJ_EVENT_GFX_GIRL_4': FR.get('OBJ_EVENT_GFX_GIRL_2', FB),
    'OBJ_EVENT_GFX_MAN_1': FR.get('OBJ_EVENT_GFX_MAN_1', FR.get('OBJ_EVENT_GFX_OLD_MAN_1', FB)),
    'OBJ_EVENT_GFX_MAN_2': FR.get('OBJ_EVENT_GFX_MAN_2', FR.get('OBJ_EVENT_GFX_OLD_MAN_2', FB)),
    'OBJ_EVENT_GFX_MAN_3': FR.get('OBJ_EVENT_GFX_MAN_1', FR.get('OBJ_EVENT_GFX_OLD_MAN_1', FB)),
    'OBJ_EVENT_GFX_MAN_4': FR.get('OBJ_EVENT_GFX_MAN_2', FR.get('OBJ_EVENT_GFX_OLD_MAN_2', FB)),
    'OBJ_EVENT_GFX_MAN_5': FR.get('OBJ_EVENT_GFX_MAN_1', FR.get('OBJ_EVENT_GFX_OLD_MAN_1', FB)),
    'OBJ_EVENT_GFX_WOMAN_4': FR.get('OBJ_EVENT_GFX_WOMAN_1', FB),
    'OBJ_EVENT_GFX_WOMAN_5': FR.get('OBJ_EVENT_GFX_WOMAN_2', FB),
    'OBJ_EVENT_GFX_WOMAN_6': FR.get('OBJ_EVENT_GFX_WOMAN_3', FB),
    'OBJ_EVENT_GFX_WOMAN_7': FR.get('OBJ_EVENT_GFX_WOMAN_1', FB),
    'OBJ_EVENT_GFX_WOMAN_8': FR.get('OBJ_EVENT_GFX_WOMAN_2', FB),
    'OBJ_EVENT_GFX_LITTLE_BOY': FR.get('OBJ_EVENT_GFX_LITTLE_BOY_1', FR.get('OBJ_EVENT_GFX_BOY_1', FB)),
    'OBJ_EVENT_GFX_LITTLE_GIRL': FR.get('OBJ_EVENT_GFX_LITTLE_GIRL_1', FR.get('OBJ_EVENT_GFX_GIRL_1', FB)),
    'OBJ_EVENT_GFX_COOK': FR.get('OBJ_EVENT_GFX_FAT_MAN', FB),
    'OBJ_EVENT_GFX_CAMERAMAN': FR.get('OBJ_EVENT_GFX_MAN_2', FR.get('OBJ_EVENT_GFX_OLD_MAN_2', FB)),
    'OBJ_EVENT_GFX_CONTEST_JUDGE': FR.get('OBJ_EVENT_GFX_OLD_MAN_1', FB),
    'OBJ_EVENT_GFX_ARTIST': FR.get('OBJ_EVENT_GFX_MAN_2', FR.get('OBJ_EVENT_GFX_OLD_MAN_2', FB)),
    'OBJ_EVENT_GFX_IN_LOVE': FR.get('OBJ_EVENT_GFX_WOMAN_1', FB),
    'OBJ_EVENT_GFX_NINJA_BOY': FR.get('OBJ_EVENT_GFX_BOY_1', FB),
    'OBJ_EVENT_GFX_TWIN': FR.get('OBJ_EVENT_GFX_TWIN', FB),
    'OBJ_EVENT_GFX_SWIMMER_M': FR.get('OBJ_EVENT_GFX_SWIMMER_M', FB),
    'OBJ_EVENT_GFX_SWIMMER_F': FR.get('OBJ_EVENT_GFX_SWIMMER_F', FB),
    'OBJ_EVENT_GFX_EXPERT_M': FR.get('OBJ_EVENT_GFX_OLD_MAN_1', FB),
    'OBJ_EVENT_GFX_EXPERT_F': FR.get('OBJ_EVENT_GFX_OLD_WOMAN', FR.get('OBJ_EVENT_GFX_WOMAN_3', FB)),
    'OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M': FR.get('OBJ_EVENT_GFX_YOUNGSTER', FB),
    'OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F': FR.get('OBJ_EVENT_GFX_LASS', FB),
    'OBJ_EVENT_GFX_TUBER_M': FR.get('OBJ_EVENT_GFX_BOY_1', FB),
    'OBJ_EVENT_GFX_TUBER_M_SWIMMING': 0,
    'OBJ_EVENT_GFX_TUBER_F_SWIMMING': 0,
    'OBJ_EVENT_GFX_SCHOOL_KID_M': FR.get('OBJ_EVENT_GFX_BOY_1', FB),
    'OBJ_EVENT_GFX_SCHOOL_KID_F': FR.get('OBJ_EVENT_GFX_GIRL_1', FB),
    'OBJ_EVENT_GFX_HEX_MANIAC': FR.get('OBJ_EVENT_GFX_WOMAN_3', FB),
    'OBJ_EVENT_GFX_POKEFAN_M': FR.get('OBJ_EVENT_GFX_FAT_MAN', FB),
    'OBJ_EVENT_GFX_POKEFAN_F': FR.get('OBJ_EVENT_GFX_WOMAN_1', FB),
    'OBJ_EVENT_GFX_MANIAC': FR.get('OBJ_EVENT_GFX_HIKER', FB),
    'OBJ_EVENT_GFX_RANGER_M': FR.get('OBJ_EVENT_GFX_COOLTRAINER_M', FB),
    'OBJ_EVENT_GFX_RANGER_F': FR.get('OBJ_EVENT_GFX_COOLTRAINER_F', FB),
    'OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M': 0,
    'OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F': 0,
    'OBJ_EVENT_GFX_OLD_WOMAN': FR.get('OBJ_EVENT_GFX_OLD_WOMAN', FR.get('OBJ_EVENT_GFX_WOMAN_3', FB)),
    'OBJ_EVENT_GFX_COOLTRAINER_M': FR.get('OBJ_EVENT_GFX_COOLTRAINER_M', FB),
    'OBJ_EVENT_GFX_COOLTRAINER_F': FR.get('OBJ_EVENT_GFX_COOLTRAINER_F', FB),
    'OBJ_EVENT_GFX_SCIENTIST_1': FR.get('OBJ_EVENT_GFX_SCIENTIST', FR.get('OBJ_EVENT_GFX_OLD_MAN_1', FB)),
    'OBJ_EVENT_GFX_SCIENTIST_2': FR.get('OBJ_EVENT_GFX_SCIENTIST', FR.get('OBJ_EVENT_GFX_OLD_MAN_1', FB)),
    'OBJ_EVENT_GFX_PSYCHIC': FR.get('OBJ_EVENT_GFX_SUPER_NERD', FR.get('OBJ_EVENT_GFX_BOY_2', FB)),
    'OBJ_EVENT_GFX_RICH_BOY': FR.get('OBJ_EVENT_GFX_BOY_2', FB),
    'OBJ_EVENT_GFX_BIRD': 0,
    'OBJ_EVENT_GFX_LINK_BRENDAN': 0,
    'OBJ_EVENT_GFX_LINK_MAY': 0,
    'OBJ_EVENT_GFX_CLERK': FR.get('OBJ_EVENT_GFX_CLERK', FB),
    # Objects to hide
    'OBJ_EVENT_GFX_BERRY_TREE': 0,
    'OBJ_EVENT_GFX_BERRY_TREE_EARLY': 0,
    'OBJ_EVENT_GFX_BERRY_TREE_MID': 0,
    'OBJ_EVENT_GFX_BERRY_TREE_LATE': 0,
    'OBJ_EVENT_GFX_BREAKABLE_ROCK': 0,
    'OBJ_EVENT_GFX_CABLE_CAR': 0,
    'OBJ_EVENT_GFX_SS_TIDAL': 0,
    'OBJ_EVENT_GFX_TRUCK': 0,
    'OBJ_EVENT_GFX_BIRCHS_BAG': FR.get('OBJ_EVENT_GFX_ITEM_BALL', FB),
    # Pokemon
    'OBJ_EVENT_GFX_AZUMARILL': FR.get('OBJ_EVENT_GFX_ITEM_BALL', FB),
    'OBJ_EVENT_GFX_AZURILL': FR.get('OBJ_EVENT_GFX_ITEM_BALL', FB),
    'OBJ_EVENT_GFX_POOCHYENA': FR.get('OBJ_EVENT_GFX_ITEM_BALL', FB),
    'OBJ_EVENT_GFX_WINGULL': FR.get('OBJ_EVENT_GFX_ITEM_BALL', FB),
    'OBJ_EVENT_GFX_SKITTY': FR.get('OBJ_EVENT_GFX_ITEM_BALL', FB),
    'OBJ_EVENT_GFX_KECLEON': 0,
    'OBJ_EVENT_GFX_KYOGRE': 0,
    'OBJ_EVENT_GFX_GROUDON': 0,
    'OBJ_EVENT_GFX_RAYQUAZA': 0,
    'OBJ_EVENT_GFX_ZIGZAGOON': FR.get('OBJ_EVENT_GFX_ITEM_BALL', FB),
    'OBJ_EVENT_GFX_DEOXYS': 0,
    'OBJ_EVENT_GFX_MEW': 0,
    'OBJ_EVENT_GFX_LATIOS': 0,
    'OBJ_EVENT_GFX_LATIAS': 0,
    'OBJ_EVENT_GFX_REGI': 0,
    'OBJ_EVENT_GFX_HO_OH': 0,
    'OBJ_EVENT_GFX_LUGIA': 0,
    'OBJ_EVENT_GFX_SUDOWOODO': 0,
}
COMPLETE.update(manual)

# Print the complete map as Python dict
print("COMPLETE_GFX_MAP = {")
for name in sorted(COMPLETE):
    print(f"    '{name}': {COMPLETE[name]},")
print("}")
print(f"\n# Total mapped: {len(COMPLETE)}, Ruby total: {len(rb)}")
print(f"# Unmapped Ruby GFX names:")
for name in sorted(rb):
    if name not in COMPLETE:
        print(f"#   {name} = {rb[name]}")
