PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MOM: …Right.\n"
    .string "All boys leave home someday.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MOM: …Right.\n"
    .string "All girls dream of traveling.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MOM: {PLAYER}!\n"
    .string "You should take a quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "There's a movie on TV.\n"
    .string "Four boys are walking on railroad\l"
    .string "tracks.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "There's a movie on TV.\n"
    .string "A girl with her hair in pigtails is\l"
    .string "walking up a brick road.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

PalletTown_PlayersHouse_1F_Text_MomHoennUpgrade::
    .string "MOM: Oh, {PLAYER}!\p"
    .string "I was watching TV and they\n"
    .string "were talking about a far-off\l"
    .string "region called HOENN!\p"
    .string "It looks like a wonderful place\n"
    .string "full of new POKéMON!\p"
    .string "I got some data about it and\n"
    .string "upgraded your TOWN MAP!\p"
    .string "You should check it out,\n"
    .string "CHAMPION!$"

PalletTown_PlayersHouse_1F_Text_MomTownMapUpgraded::
    .string "{PLAYER}'s TOWN MAP was\n"
    .string "upgraded with HOENN data!$"

PalletTown_PlayersHouse_1F_Text_MomHoennReminder::
    .string "MOM: Have you been to HOENN\n"
    .string "yet? Check your TOWN MAP!\p"
    .string "Take care out there,\n"
    .string "sweetie!$"

